# FILE: launcher/main.py
# VERSION: 1.2.1
# START_MODULE_CONTRACT
#   PURPOSE: Provide the profile-aware launcher CLI for inspecting, planning, validating, executing, and dispatching runtime contours.
#   SCOPE: CLI parsing and command dispatch for inspect, plan-run, doctor, bootstrap-env, check-env, exec, create-env, and universal interactive launch flows including CUDA-aware Qwen environment bootstrap verification
#   DEPENDS: M-PROFILES
#   LINKS: M-LAUNCHER
#   ROLE: SCRIPT
#   MAP_MODE: LOCALS
# END_MODULE_CONTRACT
#
# START_MODULE_MAP
#   FAMILY_IMPORT_CHECKS - Runtime import probes keyed by supported profile family
#   _entrypoint_to_command - Translate a configured module entrypoint into an interpreter command
#   _build_compiled_requirements_preview - Build preview lines for the resolved dependency pack file
#   _compiled_requirements_payload - Serialize resolved dependency-pack metadata for operator-facing JSON output
#   _resolved_pack_refs - Extract normalized resolved dependency pack refs from launcher metadata.
#   _needs_qwen_cuda_torch_bootstrap - Decide whether the resolved launch profile requires CUDA-specific Torch bootstrap.
#   _qwen_fast_addon_path - Resolve the optional qwen_fast add-on dependency pack path.
#   _build_runtime_bootstrap_steps - Build pre-requirements pip install commands for runtime-specific bootstrap dependencies.
#   _probe_torch_runtime - Inspect the resolved interpreter for Torch version and CUDA visibility after bootstrap.
#   _write_compiled_requirements_file - Materialize a temporary compiled requirements file for create-env execution
#   _interactive_launcher_command - Build the platform-specific wrapper command for the universal interactive launch entrypoint
#   _interactive_launcher_env - Build the environment overrides required by the universal interactive launch entrypoint
#   _venv_creation_command - Build the host-aware command used to create an isolated family environment.
#   _load_model_specs - Lazily load model specs so env-planning commands do not import runtime-heavy modules during launcher bootstrap.
#   parse_args - Parse launcher CLI arguments and subcommands
#   main - Resolve the requested launcher command and emit JSON payloads or process exit codes
# END_MODULE_MAP
#
# START_CHANGE_SUMMARY
#   LAST_CHANGE: [v1.2.2 - Made create-env use a host-aware venv creation command while preserving deferred runtime imports for env-planning flows]
# END_CHANGE_SUMMARY

from __future__ import annotations

import argparse
import json
import os
import platform
import subprocess
import sys
import tempfile
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from profiles import ProfileResolver

FAMILY_IMPORT_CHECKS = {
    "qwen": (
        "import importlib.util; import json; print(json.dumps({'torch': importlib.util.find_spec('torch') is not None, 'qwen_tts': importlib.util.find_spec('qwen_tts') is not None}))",
    ),
    "piper": (
        "import importlib.util; import json; print(json.dumps({'onnxruntime': importlib.util.find_spec('onnxruntime') is not None, 'piper': importlib.util.find_spec('piper') is not None or importlib.util.find_spec('piper_tts') is not None}))",
    ),
    "omnivoice": (
        "import importlib.util; import json; print(json.dumps({'torch': importlib.util.find_spec('torch') is not None, 'omnivoice': importlib.util.find_spec('omnivoice') is not None}))",
    ),
}

RUNTIME_BINDING_ENV_BY_MODE = {
    "custom": "TTS_DEFAULT_CUSTOM_MODEL",
    "design": "TTS_DEFAULT_DESIGN_MODEL",
    "clone": "TTS_DEFAULT_CLONE_MODEL",
}


# START_CONTRACT: _entrypoint_to_command
#   PURPOSE: Translate a configured module entrypoint into the exact command executed by the resolved interpreter.
#   INPUTS: { entrypoint: str - configured module entrypoint, python_path: str - resolved interpreter path }
#   OUTPUTS: { list[str] - subprocess-safe command sequence }
#   SIDE_EFFECTS: none
#   LINKS: M-LAUNCHER, M-PROFILE-RESOLVER
# END_CONTRACT: _entrypoint_to_command
def _entrypoint_to_command(entrypoint: str, python_path: str) -> list[str]:
    prefix = "python -m "
    if entrypoint.startswith(prefix):
        return [python_path, "-m", entrypoint[len(prefix) :]]
    return [python_path, entrypoint]


# START_CONTRACT: _build_compiled_requirements_preview
#   PURPOSE: Build the human-readable preview used for compiled dependency pack output.
#   INPUTS: { resolved: object - resolved launch profile carrying family, module, host, and metadata fields }
#   OUTPUTS: { list[str] - preview file lines suitable for a requirements-style text file }
#   SIDE_EFFECTS: none
#   LINKS: M-LAUNCHER, M-PROFILE-RESOLVER
# END_CONTRACT: _build_compiled_requirements_preview
def _build_compiled_requirements_preview(resolved: object) -> list[str]:
    pack_files = [Path(item) for item in resolved.metadata.get("pack_files", [])]
    lines = [
        "# generated by launcher",
        f"# family: {resolved.family.key}",
        f"# module: {resolved.module.key}",
        f"# platform: {resolved.host.platform_system.lower()}/{resolved.host.architecture.lower()}",
        "",
    ]
    lines.extend(f"-r {pack_file.resolve().as_posix()}" for pack_file in pack_files)
    return lines


# START_CONTRACT: _compiled_requirements_payload
#   PURPOSE: Serialize compiled dependency-pack metadata for launcher JSON responses.
#   INPUTS: { resolved: object - resolved launch profile carrying dependency metadata }
#   OUTPUTS: { dict[str, object] - JSON-serializable dependency plan payload }
#   SIDE_EFFECTS: none
#   LINKS: M-LAUNCHER, M-PROFILE-RESOLVER
# END_CONTRACT: _compiled_requirements_payload
def _compiled_requirements_payload(resolved: object) -> dict[str, object]:
    return {
        "pack_refs": resolved.metadata.get("pack_refs", {}),
        "pack_files": list(resolved.metadata.get("pack_files", [])),
        "preview_lines": _build_compiled_requirements_preview(resolved),
    }


# START_CONTRACT: _resolved_pack_refs
#   PURPOSE: Extract normalized resolved dependency pack references from launcher metadata.
#   INPUTS: { resolved: object - resolved launch profile carrying metadata.pack_refs }
#   OUTPUTS: { dict[str, tuple[str, ...]] - normalized pack refs grouped by category }
#   SIDE_EFFECTS: none
#   LINKS: M-LAUNCHER, M-PROFILE-RESOLVER
# END_CONTRACT: _resolved_pack_refs
def _resolved_pack_refs(resolved: object) -> dict[str, tuple[str, ...]]:
    raw_pack_refs = resolved.metadata.get("pack_refs", {})
    return {
        str(category): tuple(str(value) for value in values)
        for category, values in dict(raw_pack_refs).items()
    }


# START_CONTRACT: _needs_qwen_cuda_torch_bootstrap
#   PURPOSE: Decide whether a resolved Qwen launch profile requires CUDA-specific Torch bootstrap before general dependency installation.
#   INPUTS: { resolved: object - resolved launch profile carrying family metadata and resolved pack refs }
#   OUTPUTS: { bool - true when the profile targets Qwen on a CUDA contour }
#   SIDE_EFFECTS: none
#   LINKS: M-LAUNCHER, M-PROFILE-RESOLVER
# END_CONTRACT: _needs_qwen_cuda_torch_bootstrap
def _needs_qwen_cuda_torch_bootstrap(resolved: object) -> bool:
    if resolved.family.key != "qwen":
        return False
    platform_refs = _resolved_pack_refs(resolved).get("platform", ())
    return "cuda" in platform_refs


# START_CONTRACT: _qwen_fast_addon_path
#   PURPOSE: Resolve the optional qwen_fast add-on dependency pack used for CUDA Qwen contours.
#   INPUTS: { resolved: object - resolved launch profile carrying repository root metadata }
#   OUTPUTS: { Path - absolute path to the qwen_fast add-on pack file }
#   SIDE_EFFECTS: none
#   LINKS: M-LAUNCHER, M-PROFILE-RESOLVER
# END_CONTRACT: _qwen_fast_addon_path
def _qwen_fast_addon_path(resolved: object) -> Path:
    project_root = Path(str(resolved.metadata.get("project_root", Path.cwd())))
    return project_root / "profiles" / "packs" / "family" / "qwen-fast-addon.txt"


# START_CONTRACT: _build_runtime_bootstrap_steps
#   PURPOSE: Build runtime-specific pip bootstrap commands that must run before the compiled dependency pack installation.
#   INPUTS: { resolved: object - resolved launch profile, python_path: str - resolved interpreter path }
#   OUTPUTS: { list[list[str]] - subprocess-safe command sequences for pre-requirements installation }
#   SIDE_EFFECTS: none
#   LINKS: M-LAUNCHER, M-PROFILE-RESOLVER
# END_CONTRACT: _build_runtime_bootstrap_steps
def _build_runtime_bootstrap_steps(resolved: object, python_path: str) -> list[list[str]]:
    if not _needs_qwen_cuda_torch_bootstrap(resolved):
        return []

    return [
        [
            python_path,
            "-m",
            "pip",
            "install",
            "torch>=2.6",
            "torchaudio>=2.6",
            "--index-url",
            "https://download.pytorch.org/whl/cu128",
        ],
        [
            python_path,
            "-m",
            "pip",
            "install",
            "-r",
            str(_qwen_fast_addon_path(resolved)),
        ],
    ]


# START_CONTRACT: _probe_torch_runtime
#   PURPOSE: Probe the resolved interpreter for Torch install details and CUDA visibility after environment bootstrap.
#   INPUTS: { python_path: str - resolved interpreter path }
#   OUTPUTS: { dict[str, object] - JSON-serializable Torch runtime probe payload }
#   SIDE_EFFECTS: Executes the resolved interpreter in a subprocess
#   LINKS: M-LAUNCHER
# END_CONTRACT: _probe_torch_runtime
def _probe_torch_runtime(python_path: str) -> dict[str, object]:
    probe_code = "\n".join(
        [
            "import importlib.util",
            "import json",
            "torch_spec = importlib.util.find_spec('torch')",
            "payload = {'torch_installed': torch_spec is not None}",
            "if torch_spec is None:",
            "    print(json.dumps(payload))",
            "    raise SystemExit(0)",
            "import torch",
            "payload.update({",
            "    'torch_version': getattr(torch, '__version__', None),",
            "    'cuda_available': bool(torch.cuda.is_available()),",
            "    'cuda_version': getattr(torch.version, 'cuda', None),",
            "    'device_count': int(torch.cuda.device_count()) if torch.cuda.is_available() else 0,",
            "})",
            "print(json.dumps(payload))",
        ]
    )
    completed = subprocess.run(
        [python_path, "-c", probe_code],
        capture_output=True,
        text=True,
        check=False,
    )
    payload: dict[str, object] = {
        "returncode": completed.returncode,
        "stderr": completed.stderr.strip(),
    }
    if completed.stdout.strip():
        try:
            payload["stdout"] = json.loads(completed.stdout.strip())
        except Exception:
            payload["stdout"] = {"raw_stdout": completed.stdout.strip()}
    else:
        payload["stdout"] = None
    return payload


# START_CONTRACT: _write_compiled_requirements_file
#   PURPOSE: Materialize a temporary compiled requirements file for create-env execution.
#   INPUTS: { resolved: object - resolved launch profile carrying dependency metadata }
#   OUTPUTS: { str - temporary requirements file path }
#   SIDE_EFFECTS: Creates a temporary file on disk that callers are responsible for removing
#   LINKS: M-LAUNCHER, M-PROFILE-RESOLVER
# END_CONTRACT: _write_compiled_requirements_file
def _write_compiled_requirements_file(resolved: object) -> str:
    preview_lines = _build_compiled_requirements_preview(resolved)
    handle = tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        suffix="-requirements.txt",
        prefix=f"launcher-{resolved.family.key}-{resolved.module.key}-",
        delete=False,
    )
    try:
        handle.write("\n".join(preview_lines) + "\n")
    finally:
        handle.close()
    return handle.name


# START_CONTRACT: _interactive_launcher_command
#   PURPOSE: Build the platform-specific wrapper command for the universal interactive launch entrypoint.
#   INPUTS: { project_root: Path - repository root used to resolve wrapper scripts, platform_system: str | None - optional host platform override for deterministic tests }
#   OUTPUTS: { list[str] - subprocess-safe wrapper command }
#   SIDE_EFFECTS: none
#   LINKS: M-LAUNCHER, M-WINDOWS-LAUNCHER, M-WINDOWS-LAUNCHER-CMD, M-MACOS-LAUNCHER, M-LINUX-LAUNCHER
# END_CONTRACT: _interactive_launcher_command
def _interactive_launcher_command(
    project_root: Path, platform_system: str | None = None
) -> list[str]:
    detected_platform = (platform_system or platform.system()).lower()
    scripts_root = project_root / "scripts"

    if detected_platform == "windows":
        return ["cmd.exe", "/c", str(scripts_root / "launch-windows.cmd")]
    if detected_platform == "darwin":
        return ["bash", str(scripts_root / "launch-macos.sh")]
    if detected_platform == "linux":
        return ["bash", str(scripts_root / "launch-linux.sh")]

    raise ValueError(f"Unsupported interactive launcher platform: {detected_platform}")


# START_CONTRACT: _interactive_launcher_env
#   PURPOSE: Build the environment overrides required by the universal interactive launch entrypoint.
#   INPUTS: { project_root: Path - repository root used by wrapper fallbacks }
#   OUTPUTS: { dict[str, str] - environment mapping for wrapper delegation }
#   SIDE_EFFECTS: Reads current process environment
#   LINKS: M-LAUNCHER, M-WINDOWS-LAUNCHER-CMD
# END_CONTRACT: _interactive_launcher_env
def _interactive_launcher_env(project_root: Path) -> dict[str, str]:
    env = dict(os.environ)
    env.setdefault("TTS_LAUNCH_PROJECT_ROOT", str(project_root))
    return env


def _venv_creation_command(env_root: Path) -> list[str]:
    if platform.system().lower() == "windows":
        return ["py", "-3.11", "-m", "venv", str(env_root)]
    return [sys.executable, "-m", "venv", str(env_root)]


def _load_model_specs() -> Mapping[str, Any]:
    from core.models.catalog import MODEL_SPECS

    return MODEL_SPECS


def _runtime_bindings_payload(resolved: object) -> dict[str, object]:
    model_specs = _load_model_specs()
    default_bindings_by_family = {
        "piper": {
            "custom_model": next(
                (
                    spec.model_id
                    for spec in model_specs.values()
                    if spec.family == "Piper" and spec.mode == "custom"
                ),
                None,
            ),
            "design_model": None,
            "clone_model": None,
        },
        "omnivoice": {
            "custom_model": next(
                (
                    spec.model_id
                    for spec in model_specs.values()
                    if spec.family == "OmniVoice" and spec.mode == "custom"
                ),
                None,
            ),
            "design_model": next(
                (
                    spec.model_id
                    for spec in model_specs.values()
                    if spec.family == "OmniVoice" and spec.mode == "design"
                ),
                None,
            ),
            "clone_model": next(
                (
                    spec.model_id
                    for spec in model_specs.values()
                    if spec.family == "OmniVoice" and spec.mode == "clone"
                ),
                None,
            ),
        },
    }.get(resolved.family.key, {})

    bindings = {
        "family": os.environ.get("TTS_ACTIVE_FAMILY") or resolved.family.key,
        "custom_model": os.environ.get("TTS_DEFAULT_CUSTOM_MODEL")
        or default_bindings_by_family.get("custom_model"),
        "design_model": os.environ.get("TTS_DEFAULT_DESIGN_MODEL")
        or default_bindings_by_family.get("design_model"),
        "clone_model": os.environ.get("TTS_DEFAULT_CLONE_MODEL")
        or default_bindings_by_family.get("clone_model"),
    }
    capability_status = {}
    for mode, env_name in RUNTIME_BINDING_ENV_BY_MODE.items():
        bound_model = bindings[f"{mode}_model"]
        capability_status[mode] = {
            "bound": bound_model is not None,
            "model": bound_model,
            "env_var": env_name,
        }
    return {
        "bindings": bindings,
        "capability_status": capability_status,
    }


# START_CONTRACT: parse_args
#   PURPOSE: Parse launcher CLI arguments and select the requested profile-aware command.
#   INPUTS: none
#   OUTPUTS: { argparse.Namespace - parsed launcher command payload }
#   SIDE_EFFECTS: Reads process CLI arguments through argparse
#   LINKS: M-LAUNCHER
# END_CONTRACT: parse_args
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Profile-aware runtime launcher")
    parser.add_argument(
        "--project-root",
        help="override the repository root used to resolve profiles and isolated family environments",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser(
        "launch",
        help="dispatch to the existing interactive platform launcher wrapper for the current host",
    )

    inspect_parser = subparsers.add_parser(
        "inspect",
        help="resolve a host+family+module launch profile and print it as JSON",
    )
    inspect_parser.add_argument("--family", required=True)
    inspect_parser.add_argument("--module", required=True)

    plan_run_parser = subparsers.add_parser(
        "plan-run",
        help="build an operator-facing launch plan for a resolved family+module profile",
    )
    plan_run_parser.add_argument("--family", required=True)
    plan_run_parser.add_argument("--module", required=True)

    doctor_parser = subparsers.add_parser(
        "doctor",
        help="inspect whether the expected isolated family environment and runtime pack are present",
    )
    doctor_parser.add_argument("--family", required=True)
    doctor_parser.add_argument("--module", required=True)

    bootstrap_parser = subparsers.add_parser(
        "bootstrap-env",
        help="print the exact environment bootstrap commands for a resolved family contour",
    )
    bootstrap_parser.add_argument("--family", required=True)
    bootstrap_parser.add_argument("--module", required=True)

    check_env_parser = subparsers.add_parser(
        "check-env",
        help="verify an existing isolated family environment and basic runtime imports",
    )
    check_env_parser.add_argument("--family", required=True)
    check_env_parser.add_argument("--module", required=True)

    exec_parser = subparsers.add_parser(
        "exec",
        help="execute a module entrypoint through the resolved family interpreter, or print the command in dry-run mode",
    )
    exec_parser.add_argument("--family", required=True)
    exec_parser.add_argument("--module", required=True)
    exec_parser.add_argument("--dry-run", action="store_true")

    create_env_parser = subparsers.add_parser(
        "create-env",
        help="create the resolved isolated family environment and install its runtime pack when --apply is passed",
    )
    create_env_parser.add_argument("--family", required=True)
    create_env_parser.add_argument("--module", required=True)
    create_env_parser.add_argument("--apply", action="store_true")
    return parser.parse_args()


# START_CONTRACT: main
#   PURPOSE: Execute the requested launcher command against a resolved family and module profile.
#   INPUTS: none
#   OUTPUTS: { int - process exit code for the selected launcher flow }
#   SIDE_EFFECTS: Resolves host and runtime profiles, prints JSON payloads, and may spawn subprocesses for env or entrypoint execution
#   LINKS: M-LAUNCHER, M-PROFILE-RESOLVER
# END_CONTRACT: main
def main() -> int:
    # START_BLOCK_RESOLVE_COMMAND_CONTEXT
    args = parse_args()
    resolver = (
        ProfileResolver(Path(args.project_root).resolve())
        if args.project_root
        else ProfileResolver()
    )
    # END_BLOCK_RESOLVE_COMMAND_CONTEXT

    # START_BLOCK_DISPATCH_COMMAND
    if args.command == "launch":
        project_root = (
            Path(args.project_root).resolve() if args.project_root else Path.cwd().resolve()
        )
        try:
            command = _interactive_launcher_command(project_root)
        except ValueError as exc:
            print(
                json.dumps(
                    {
                        "launch": {
                            "project_root": str(project_root),
                            "platform": platform.system().lower(),
                            "error": "unsupported_platform",
                            "message": str(exc),
                        }
                    },
                    ensure_ascii=False,
                    indent=2,
                )
            )
            return 1
        completed = subprocess.run(
            command,
            cwd=str(project_root),
            env=_interactive_launcher_env(project_root),
            check=False,
        )
        return completed.returncode
    if args.command == "inspect":
        resolved = resolver.resolve(family=args.family, module=args.module)
        payload = resolved.to_dict()
        payload["runtime_bindings"] = _runtime_bindings_payload(resolved)
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 0
    if args.command == "plan-run":
        resolved = resolver.resolve(family=args.family, module=args.module)
        payload = resolved.to_dict()
        payload["runtime_bindings"] = _runtime_bindings_payload(resolved)
        payload["launch_plan"] = {
            "family": resolved.family.key,
            "module": resolved.module.key,
            "required_env_name": resolved.required_env_name,
            "expected_python_path": resolved.expected_python_path,
            "dependency_plan": _compiled_requirements_payload(resolved),
            "entrypoint": resolved.module.entrypoint,
            "selected_backend": resolved.selected_backend,
            "backend_candidates": list(resolved.backend_candidates),
            "compatible": resolved.compatible,
            "reasons": list(resolved.reasons),
            "runtime_bindings": payload["runtime_bindings"],
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 0
    if args.command == "doctor":
        resolved = resolver.resolve(family=args.family, module=args.module)
        pack_files = [Path(item) for item in resolved.metadata.get("pack_files", [])]
        expected_python = Path(resolved.expected_python_path or "")
        env_root = (
            expected_python.parent.parent
            if expected_python.name.lower() == "python.exe"
            else expected_python.parent.parent
        )
        checks = {
            "pack_files_exist": all(pack_file.exists() for pack_file in pack_files),
            "expected_env_root_exists": env_root.exists(),
            "expected_python_exists": expected_python.exists(),
        }
        missing_steps = []
        missing_pack_files = [str(pack_file) for pack_file in pack_files if not pack_file.exists()]
        if missing_pack_files:
            missing_steps.append("dependency_pack_missing_from_repo")
        if not checks["expected_env_root_exists"]:
            missing_steps.append(f"create_env:{env_root}")
        if checks["expected_env_root_exists"] and not checks["expected_python_exists"]:
            missing_steps.append(f"python_missing_in_env:{expected_python}")
        payload = resolved.to_dict()
        payload["runtime_bindings"] = _runtime_bindings_payload(resolved)
        payload["doctor"] = {
            "family": resolved.family.key,
            "module": resolved.module.key,
            "pack_files": [str(pack_file) for pack_file in pack_files],
            "missing_pack_files": missing_pack_files,
            "compiled_requirements": _compiled_requirements_payload(resolved),
            "expected_env_root": str(env_root),
            "expected_python_path": str(expected_python),
            "checks": checks,
            "missing_steps": missing_steps,
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 0
    if args.command == "bootstrap-env":
        resolved = resolver.resolve(family=args.family, module=args.module)
        env_root = Path(resolved.expected_python_path).parent.parent
        runtime_bootstrap_steps = _build_runtime_bootstrap_steps(
            resolved, resolved.expected_python_path
        )
        create_env_command = _venv_creation_command(env_root)
        bootstrap = {
            "family": resolved.family.key,
            "module": resolved.module.key,
            "expected_env_root": str(env_root),
            "expected_python_path": resolved.expected_python_path,
            "compiled_requirements": _compiled_requirements_payload(resolved),
            "backend_candidates": list(resolved.backend_candidates),
            "suggested_backend_env": resolved.selected_backend,
            "commands": {
                "create_env": " ".join(create_env_command),
                "set_backend": f"set TTS_BACKEND={resolved.selected_backend}"
                if resolved.selected_backend
                else None,
                "upgrade_pip": f"{resolved.expected_python_path} -m pip install --upgrade pip",
                "runtime_bootstrap": [" ".join(step) for step in runtime_bootstrap_steps],
                "install_compiled_requirements": f"{resolved.expected_python_path} -m pip install -r <temp compiled requirements file>",
            },
        }
        payload = resolved.to_dict()
        payload["runtime_bindings"] = _runtime_bindings_payload(resolved)
        payload["bootstrap_env"] = bootstrap
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 0
    if args.command == "check-env":
        resolved = resolver.resolve(family=args.family, module=args.module)
        expected_python = Path(resolved.expected_python_path or "")
        env_exists = expected_python.parent.parent.exists()
        python_exists = expected_python.exists()
        import_check = None
        if python_exists:
            command = [str(expected_python), "-c", *FAMILY_IMPORT_CHECKS[resolved.family.key]]
            completed = subprocess.run(command, capture_output=True, text=True, check=False)
            parsed = None
            if completed.stdout:
                try:
                    parsed = json.loads(completed.stdout.strip())
                except Exception:
                    parsed = {"raw_stdout": completed.stdout.strip()}
            import_check = {
                "returncode": completed.returncode,
                "stdout": parsed,
                "stderr": completed.stderr.strip(),
            }
        payload = resolved.to_dict()
        payload["runtime_bindings"] = _runtime_bindings_payload(resolved)
        payload["check_env"] = {
            "family": resolved.family.key,
            "module": resolved.module.key,
            "expected_python_path": str(expected_python),
            "checks": {
                "expected_env_root_exists": env_exists,
                "expected_python_exists": python_exists,
            },
            "compiled_requirements": _compiled_requirements_payload(resolved),
            "import_check": import_check,
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 0
    if args.command == "exec":
        resolved = resolver.resolve(family=args.family, module=args.module)
        expected_python = Path(resolved.expected_python_path or "")
        command = _entrypoint_to_command(resolved.module.entrypoint, str(expected_python))
        payload = resolved.to_dict()
        payload["runtime_bindings"] = _runtime_bindings_payload(resolved)
        payload["exec"] = {
            "family": resolved.family.key,
            "module": resolved.module.key,
            "command": command,
            "dry_run": bool(args.dry_run),
            "python_exists": expected_python.exists(),
            "runtime_bindings": payload["runtime_bindings"],
        }
        if args.dry_run:
            print(json.dumps(payload, ensure_ascii=False, indent=2))
            return 0
        if not expected_python.exists():
            payload["exec"]["error"] = "expected_python_missing"
            print(json.dumps(payload, ensure_ascii=False, indent=2))
            return 1
        completed = subprocess.run(command, check=False)
        return completed.returncode
    if args.command == "create-env":
        resolved = resolver.resolve(family=args.family, module=args.module)
        expected_python = Path(resolved.expected_python_path or "")
        env_root = expected_python.parent.parent
        payload = resolved.to_dict()
        payload["runtime_bindings"] = _runtime_bindings_payload(resolved)
        compiled_requirements_path = _write_compiled_requirements_file(resolved)
        runtime_bootstrap_steps = _build_runtime_bootstrap_steps(resolved, str(expected_python))
        create_env_command = _venv_creation_command(env_root)
        payload["create_env"] = {
            "family": resolved.family.key,
            "module": resolved.module.key,
            "apply": bool(args.apply),
            "expected_env_root": str(env_root),
            "expected_python_path": str(expected_python),
            "compiled_requirements_path": compiled_requirements_path,
            "compiled_requirements": _compiled_requirements_payload(resolved),
            "runtime_bootstrap_steps": runtime_bootstrap_steps,
            "runtime_bindings": payload["runtime_bindings"],
            "steps": [
                create_env_command,
                [str(expected_python), "-m", "pip", "install", "--upgrade", "pip"],
                [str(expected_python), "-m", "pip", "install", "-r", compiled_requirements_path],
            ],
            "env_already_exists": expected_python.exists(),
        }
        if not args.apply:
            print(json.dumps(payload, ensure_ascii=False, indent=2))
            return 0
        _, upgrade_pip_command, install_compiled_requirements_command = payload["create_env"][
            "steps"
        ]
        try:
            if not expected_python.exists():
                subprocess.run(create_env_command, check=True)
            subprocess.run(
                upgrade_pip_command,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            for bootstrap_command in runtime_bootstrap_steps:
                subprocess.run(
                    bootstrap_command,
                    check=True,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                )
            subprocess.run(
                install_compiled_requirements_command,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
        except subprocess.CalledProcessError as exc:
            payload["create_env"]["created"] = expected_python.exists()
            payload["create_env"]["error"] = {
                "step": (
                    "install_compiled_requirements"
                    if exc.cmd == install_compiled_requirements_command
                    else "runtime_bootstrap"
                    if exc.cmd in runtime_bootstrap_steps
                    else "upgrade_pip"
                    if exc.cmd == upgrade_pip_command
                    else "bootstrap"
                ),
                "command": exc.cmd,
                "returncode": exc.returncode,
                "stdout": (exc.stdout or "").strip(),
                "stderr": (exc.stderr or "").strip(),
            }
            print(json.dumps(payload, ensure_ascii=False, indent=2))
            Path(compiled_requirements_path).unlink(missing_ok=True)
            return 1
        payload["create_env"]["created"] = expected_python.exists()
        payload["create_env"]["torch_runtime_probe"] = _probe_torch_runtime(str(expected_python))
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        Path(compiled_requirements_path).unlink(missing_ok=True)
        return 0
    # END_BLOCK_DISPATCH_COMMAND
    raise ValueError(f"Unsupported launcher command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
