# FILE: tests/unit/scripts/test_launcher_doctor.py
# VERSION: 1.1.1
# START_MODULE_CONTRACT
#   PURPOSE: Validate the launcher doctor command for isolated family environment diagnostics.
#   SCOPE: doctor output for runtime pack presence and expected env/python paths
#   DEPENDS: M-LAUNCHER
#   LINKS: V-M-LAUNCHER
#   ROLE: TEST
#   MAP_MODE: LOCALS
# END_MODULE_CONTRACT
#
# START_MODULE_MAP
#   _run_launcher_json - Execute a launcher command and parse its JSON payload
#   _normalized_path - Normalize path separators for host-aware suffix assertions
#   _expected_env_root_suffix - Return the canonical isolated-env root suffix for the current host
#   _expected_python_suffix - Return the canonical interpreter suffix for the current host
#   _assert_compiled_requirements - Verify compiled-requirements preview metadata and family pack references
#   _assert_doctor_payload - Verify doctor payload structure and environment-state consistency
#   test_launcher_doctor_reports_expected_qwen_env_paths - Verifies qwen doctor output uses the structured guidance envelope and host-aware interpreter path
#   test_launcher_doctor_reports_expected_omnivoice_env_paths - Verifies omnivoice doctor output uses the structured guidance envelope and host-aware interpreter path
# END_MODULE_MAP
#
# START_CHANGE_SUMMARY
#   LAST_CHANGE: [v1.1.1 - Aligned module verification links with launcher ownership while keeping doctor path and payload assertions host-aware]
# END_CHANGE_SUMMARY

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[3]

pytestmark = pytest.mark.unit


# START_CONTRACT: _run_launcher_json
#   PURPOSE: Execute a launcher command in the repository root and parse its JSON response.
#   INPUTS: { args: list[str] - launcher subcommand arguments after `python -m launcher` }
#   OUTPUTS: { dict[str, object] - parsed launcher JSON payload }
#   SIDE_EFFECTS: Spawns the launcher subprocess
#   LINKS: M-LAUNCHER
# END_CONTRACT: _run_launcher_json
def _run_launcher_json(args: list[str]) -> dict[str, object]:
    completed = subprocess.run(
        [sys.executable, "-m", "launcher", *args],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(completed.stdout)


# START_CONTRACT: _normalized_path
#   PURPOSE: Normalize launcher payload paths for cross-platform suffix assertions.
#   INPUTS: { value: str - path-like string from launcher JSON output }
#   OUTPUTS: { str - slash-normalized path }
#   SIDE_EFFECTS: none
#   LINKS: none
# END_CONTRACT: _normalized_path
def _normalized_path(value: str) -> str:
    return value.replace("\\", "/")


def _expected_env_root_suffix(env_name: str) -> str:
    return _normalized_path(str(Path(".envs") / env_name))


def _expected_python_suffix(env_name: str) -> str:
    interpreter = Path("Scripts/python.exe") if os.name == "nt" else Path("bin/python")
    return _normalized_path(str(Path(".envs") / env_name / interpreter))


def _assert_compiled_requirements(compiled: dict[str, object], *, family: str, module: str) -> None:
    preview_lines = compiled["preview_lines"]

    assert compiled["pack_refs"]["family"] == [family]
    assert any(
        _normalized_path(path).endswith(f"/profiles/packs/family/{family}.txt")
        for path in compiled["pack_files"]
    )
    assert preview_lines[0] == "# generated by launcher"
    assert preview_lines[1] == f"# family: {family}"
    assert preview_lines[2] == f"# module: {module}"
    assert preview_lines[3].startswith("# platform: ")
    assert preview_lines[4] == ""
    assert any(
        line.startswith("-r ")
        and _normalized_path(line[3:]).endswith(f"/profiles/packs/family/{family}.txt")
        for line in preview_lines
    )


# START_CONTRACT: _assert_doctor_payload
#   PURPOSE: Verify the stable doctor guidance payload shape and its cross-field consistency.
#   INPUTS: { payload: dict[str, object] - parsed launcher JSON payload, family: str - expected family key, module: str - expected module key }
#   OUTPUTS: { None - assertions only }
#   SIDE_EFFECTS: none
#   LINKS: M-LAUNCHER
# END_CONTRACT: _assert_doctor_payload
def _assert_doctor_payload(payload: dict[str, object], *, family: str, module: str) -> None:
    doctor = payload["doctor"]

    assert payload["family"]["key"] == family
    assert payload["module"]["key"] == module
    assert payload["required_env_name"] == family
    assert set(doctor) == {
        "family",
        "module",
        "pack_files",
        "missing_pack_files",
        "compiled_requirements",
        "expected_env_root",
        "expected_python_path",
        "checks",
        "missing_steps",
    }
    assert doctor["family"] == family
    assert doctor["module"] == module
    assert doctor["missing_pack_files"] == []
    assert doctor["compiled_requirements"]["pack_files"] == doctor["pack_files"]
    assert _normalized_path(doctor["expected_env_root"]).endswith(
        f"/{_expected_env_root_suffix(family)}"
    )
    assert _normalized_path(doctor["expected_python_path"]).endswith(
        f"/{_expected_python_suffix(family)}"
    )

    checks = doctor["checks"]
    assert set(checks) == {
        "pack_files_exist",
        "expected_env_root_exists",
        "expected_python_exists",
    }
    assert checks["pack_files_exist"] is True

    if checks["expected_python_exists"]:
        assert checks["expected_env_root_exists"] is True

    if not checks["expected_env_root_exists"]:
        assert doctor["missing_steps"] == [f"create_env:{doctor['expected_env_root']}"]
    elif not checks["expected_python_exists"]:
        assert doctor["missing_steps"] == [
            f"python_missing_in_env:{doctor['expected_python_path']}"
        ]
    else:
        assert doctor["missing_steps"] == []

    _assert_compiled_requirements(doctor["compiled_requirements"], family=family, module=module)


def test_launcher_doctor_reports_expected_qwen_env_paths():
    payload = _run_launcher_json(["doctor", "--family", "qwen", "--module", "server"])

    _assert_doctor_payload(payload, family="qwen", module="server")


def test_launcher_doctor_reports_expected_omnivoice_env_paths():
    payload = _run_launcher_json(["doctor", "--family", "omnivoice", "--module", "telegram"])

    _assert_doctor_payload(payload, family="omnivoice", module="telegram")
