# FILE: tests/unit/scripts/test_launcher_check_env.py
# VERSION: 1.2.0
# START_MODULE_CONTRACT
#   PURPOSE: Validate the launcher check-env command for isolated family environment verification.
#   SCOPE: environment existence, family isolation policy, shared-env warnings, and interpreter-path verification output
#   DEPENDS: M-LAUNCHER
#   LINKS: V-M-LAUNCHER
#   ROLE: TEST
#   MAP_MODE: LOCALS
# END_MODULE_CONTRACT
#
# START_MODULE_MAP
#   _run_launcher_json - Execute a launcher command and parse its JSON payload
#   _normalized_path - Normalize path separators for host-aware suffix assertions
#   _expected_python_suffix - Return the canonical interpreter suffix for the current host
#   _assert_compiled_requirements - Verify compiled-requirements preview metadata and family pack references
#   _assert_import_check_shape - Verify import probe output remains machine-readable when a family interpreter exists
#   _assert_check_env_payload - Verify check-env payload structure and environment-state consistency
#   test_launcher_check_env_reports_qwen_expected_python_path - Verifies qwen check-env output uses the structured environment envelope and host-aware interpreter path
#   test_launcher_check_env_reports_omnivoice_expected_python_path - Verifies omnivoice check-env output uses the structured environment envelope and host-aware interpreter path
# END_MODULE_MAP
#
# START_CHANGE_SUMMARY
#   LAST_CHANGE: [v1.2.0 - Added assertions for canonical per-family environment policy and shared-env detection payloads]
# END_CHANGE_SUMMARY

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[3]

pytestmark = pytest.mark.unit


# START_CONTRACT: _run_launcher_json
#   PURPOSE: Execute a launcher command in the repository root and parse its JSON response.
#   INPUTS: { args: list[str] - launcher subcommand arguments after `python -m launcher` }
#   OUTPUTS: { dict[str, object] - parsed launcher JSON payload }
#   SIDE_EFFECTS: Spawns the launcher subprocess
#   LINKS: M-LAUNCHER
# END_CONTRACT: _run_launcher_json
def _run_launcher_json(args: list[str]) -> dict[str, Any]:
    completed = subprocess.run(
        [sys.executable, "-m", "launcher", *args],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(completed.stdout)


def _normalized_path(value: str) -> str:
    return value.replace("\\", "/")


def _expected_python_suffix(env_name: str) -> str:
    interpreter = Path("Scripts/python.exe") if os.name == "nt" else Path("bin/python")
    return _normalized_path(str(Path(".envs") / env_name / interpreter))


def _assert_compiled_requirements(compiled: dict[str, Any], *, family: str, module: str) -> None:
    preview_lines = compiled["preview_lines"]

    assert compiled["pack_refs"]["family"] == [family]
    assert any(
        _normalized_path(path).endswith(f"/profiles/packs/family/{family}.txt")
        for path in compiled["pack_files"]
    )
    assert preview_lines[0] == "# generated by launcher"
    assert preview_lines[1] == f"# family: {family}"
    assert preview_lines[2] == f"# module: {module}"
    assert preview_lines[3].startswith("# platform: ")
    assert preview_lines[4] == ""
    assert any(
        line.startswith("-r ")
        and _normalized_path(line[3:]).endswith(f"/profiles/packs/family/{family}.txt")
        for line in preview_lines
    )


def _assert_import_check_shape(import_check: dict[str, Any], *, expected_keys: set[str]) -> None:
    assert set(import_check) == {"returncode", "stdout", "stderr"}
    assert isinstance(import_check["returncode"], int)
    assert isinstance(import_check["stderr"], str)

    stdout = import_check["stdout"]
    if stdout is None:
        return
    assert isinstance(stdout, dict)
    if "raw_stdout" in stdout:
        assert set(stdout) == {"raw_stdout"}
        assert isinstance(stdout["raw_stdout"], str)
        return

    assert set(stdout) == expected_keys
    assert all(isinstance(value, bool) for value in stdout.values())


# START_CONTRACT: _assert_check_env_payload
#   PURPOSE: Verify the stable check-env payload shape and optional import-probe consistency.
#   INPUTS: { payload: dict[str, object] - parsed launcher JSON payload, family: str - expected family key, module: str - expected module key, import_keys: set[str] - expected import-probe result keys when structured stdout is present }
#   OUTPUTS: { None - assertions only }
#   SIDE_EFFECTS: none
#   LINKS: M-LAUNCHER
# END_CONTRACT: _assert_check_env_payload
def _assert_check_env_payload(
    payload: dict[str, Any],
    *,
    family: str,
    module: str,
    import_keys: set[str],
) -> None:
    check_env = payload["check_env"]
    family_environment = payload["family_environment"]

    assert payload["family"]["key"] == family
    assert payload["module"]["key"] == module
    assert payload["required_env_name"] == family
    assert family_environment["environment_isolated"] is True
    assert family_environment["policy"] == "one_family_one_environment"
    assert family_environment["family"] == family
    assert family_environment["expected_env_name"] == family
    assert family_environment["expected_env_matches_family"] is True
    assert family_environment["shared_env_supported_for_runtime"] is False
    assert _normalized_path(family_environment["expected_env_root"]).endswith(
        f"/.envs/{family}"
    )
    assert _normalized_path(family_environment["expected_python_path"]).endswith(
        f"/{_expected_python_suffix(family)}"
    )
    assert _normalized_path(family_environment["legacy_shared_env_root"]).endswith(
        "/.venv311"
    )
    assert family_environment["recommended_create_env_command"][-6:] == [
        "create-env",
        "--family",
        family,
        "--module",
        module,
        "--apply",
    ]
    assert set(check_env) == {
        "family",
        "module",
        "expected_env_root",
        "expected_python_path",
        "environment_isolated",
        "family_environment",
        "checks",
        "compiled_requirements",
        "import_check",
    }
    assert check_env["family"] == family
    assert check_env["module"] == module
    assert check_env["environment_isolated"] is True
    assert check_env["family_environment"] == family_environment
    assert _normalized_path(check_env["expected_env_root"]).endswith(f"/.envs/{family}")
    assert _normalized_path(check_env["expected_python_path"]).endswith(
        f"/{_expected_python_suffix(family)}"
    )

    checks = check_env["checks"]
    assert set(checks) == {
        "expected_env_root_exists",
        "expected_python_exists",
        "expected_env_matches_family",
        "shared_env_detected",
    }
    assert checks["expected_env_matches_family"] is True
    assert checks["shared_env_detected"] == family_environment["shared_env_detected"]
    if checks["expected_python_exists"]:
        assert checks["expected_env_root_exists"] is True
        assert check_env["import_check"] is not None
        _assert_import_check_shape(check_env["import_check"], expected_keys=import_keys)
    else:
        assert check_env["import_check"] is None

    _assert_compiled_requirements(check_env["compiled_requirements"], family=family, module=module)


def test_launcher_check_env_reports_qwen_expected_python_path():
    payload = _run_launcher_json(["check-env", "--family", "qwen", "--module", "server"])

    _assert_check_env_payload(
        payload,
        family="qwen",
        module="server",
        import_keys={"torch", "qwen_tts"},
    )


def test_launcher_check_env_reports_omnivoice_expected_python_path():
    payload = _run_launcher_json(["check-env", "--family", "omnivoice", "--module", "telegram"])

    _assert_check_env_payload(
        payload,
        family="omnivoice",
        module="telegram",
        import_keys={"torch", "omnivoice"},
    )
