# FILE: tests/unit/scripts/test_launcher_bootstrap_env.py
# VERSION: 1.1.3
# START_MODULE_CONTRACT
#   PURPOSE: Validate the launcher bootstrap-env command for isolated family environment planning.
#   SCOPE: bootstrap command output for family runtime contours
#   DEPENDS: M-LAUNCHER
#   LINKS: V-M-LAUNCHER
#   ROLE: TEST
#   MAP_MODE: LOCALS
# END_MODULE_CONTRACT
#
# START_MODULE_MAP
#   _run_launcher_json - Execute a launcher command and parse its JSON payload
#   _normalized_path - Normalize path separators for host-aware suffix assertions
#   _expected_env_root_suffix - Return the canonical isolated-env root suffix for the current host
#   _expected_python_suffix - Return the canonical interpreter suffix for the current host
#   _assert_compiled_requirements - Verify compiled-requirements preview metadata and family pack references
#   _assert_bootstrap_payload - Verify bootstrap-env payload structure and the launcher's current guidance-string semantics
#   test_launcher_bootstrap_env_outputs_qwen_commands - Verifies qwen bootstrap guidance stays host-aware for paths while pinning the launcher's current command strings
#   test_launcher_bootstrap_env_outputs_omnivoice_commands - Verifies omnivoice bootstrap guidance keeps deterministic structured payload fields and current command strings
#   test_launcher_bootstrap_env_avoids_runtime_bootstrap_imports - Verifies bootstrap-env can emit JSON even when runtime-heavy imports are blocked during launcher startup.
# END_MODULE_MAP
#
# START_CHANGE_SUMMARY
#   LAST_CHANGE: [v1.1.3 - Updated bootstrap-env assertions for host-aware venv creation commands while preserving runtime-import isolation coverage]
# END_CHANGE_SUMMARY

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[3]

pytestmark = pytest.mark.unit


# START_CONTRACT: _run_launcher_json
#   PURPOSE: Execute a launcher command in the repository root and parse its JSON response.
#   INPUTS: { args: list[str] - launcher subcommand arguments after `python -m launcher` }
#   OUTPUTS: { dict[str, object] - parsed launcher JSON payload }
#   SIDE_EFFECTS: Spawns the launcher subprocess
#   LINKS: M-LAUNCHER
# END_CONTRACT: _run_launcher_json
def _run_launcher_json(args: list[str]) -> dict[str, object]:
    completed = subprocess.run(
        [sys.executable, "-m", "launcher", *args],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(completed.stdout)


def _normalized_path(value: str) -> str:
    return value.replace("\\", "/")


def _expected_env_root_suffix(env_name: str) -> str:
    return _normalized_path(str(Path(".envs") / env_name))


def _expected_python_suffix(env_name: str) -> str:
    interpreter = Path("Scripts/python.exe") if os.name == "nt" else Path("bin/python")
    return _normalized_path(str(Path(".envs") / env_name / interpreter))


def _assert_compiled_requirements(compiled: dict[str, object], *, family: str, module: str) -> None:
    preview_lines = compiled["preview_lines"]

    assert compiled["pack_refs"]["family"] == [family]
    assert any(
        _normalized_path(path).endswith(f"/profiles/packs/family/{family}.txt")
        for path in compiled["pack_files"]
    )
    assert preview_lines[0] == "# generated by launcher"
    assert preview_lines[1] == f"# family: {family}"
    assert preview_lines[2] == f"# module: {module}"
    assert preview_lines[3].startswith("# platform: ")
    assert preview_lines[4] == ""
    assert any(
        line.startswith("-r ")
        and _normalized_path(line[3:]).endswith(f"/profiles/packs/family/{family}.txt")
        for line in preview_lines
    )


# START_CONTRACT: _assert_bootstrap_payload
#   PURPOSE: Verify the stable bootstrap-env guidance payload shape and the current launcher-emitted command strings.
#   INPUTS: { payload: dict[str, object] - parsed launcher JSON payload, family: str - expected family key, module: str - expected module key }
#   OUTPUTS: { None - assertions only }
#   SIDE_EFFECTS: none
#   LINKS: M-LAUNCHER
# END_CONTRACT: _assert_bootstrap_payload
def _assert_bootstrap_payload(payload: dict[str, object], *, family: str, module: str) -> None:
    bootstrap = payload["bootstrap_env"]
    commands = bootstrap["commands"]

    assert payload["family"]["key"] == family
    assert payload["module"]["key"] == module
    assert payload["required_env_name"] == family
    assert bootstrap["family"] == family
    assert bootstrap["module"] == module
    assert set(bootstrap) == {
        "family",
        "module",
        "expected_env_root",
        "expected_python_path",
        "compiled_requirements",
        "backend_candidates",
        "suggested_backend_env",
        "commands",
    }
    assert _normalized_path(bootstrap["expected_env_root"]).endswith(
        f"/{_expected_env_root_suffix(family)}"
    )
    assert _normalized_path(bootstrap["expected_python_path"]).endswith(
        f"/{_expected_python_suffix(family)}"
    )
    assert bootstrap["backend_candidates"] == list(payload["backend_candidates"])
    assert bootstrap["suggested_backend_env"] == payload["selected_backend"]
    assert bootstrap["suggested_backend_env"] in bootstrap["backend_candidates"]

    assert set(commands) == {
        "create_env",
        "set_backend",
        "runtime_bootstrap",
        "upgrade_pip",
        "install_compiled_requirements",
    }
    expected_create_env_command = (
        f"py -3.11 -m venv {bootstrap['expected_env_root']}"
        if os.name == "nt"
        else f"{sys.executable} -m venv {bootstrap['expected_env_root']}"
    )
    assert commands["create_env"] == expected_create_env_command
    assert commands["set_backend"] == f"set TTS_BACKEND={bootstrap['suggested_backend_env']}"
    assert (
        commands["upgrade_pip"]
        == f"{bootstrap['expected_python_path']} -m pip install --upgrade pip"
    )
    assert (
        commands["install_compiled_requirements"]
        == f"{bootstrap['expected_python_path']} -m pip install -r <temp compiled requirements file>"
    )

    _assert_compiled_requirements(bootstrap["compiled_requirements"], family=family, module=module)


def test_launcher_bootstrap_env_outputs_qwen_commands():
    payload = _run_launcher_json(["bootstrap-env", "--family", "qwen", "--module", "server"])

    _assert_bootstrap_payload(payload, family="qwen", module="server")


def test_launcher_bootstrap_env_outputs_omnivoice_commands():
    payload = _run_launcher_json(["bootstrap-env", "--family", "omnivoice", "--module", "telegram"])

    _assert_bootstrap_payload(payload, family="omnivoice", module="telegram")
    assert payload["bootstrap_env"]["suggested_backend_env"] == "torch"


def test_launcher_bootstrap_env_avoids_runtime_bootstrap_imports(tmp_path: Path):
    sitecustomize_path = tmp_path / "sitecustomize.py"
    sitecustomize_path.write_text(
        "import builtins\n"
        "import os\n"
        "\n"
        "_real_import = builtins.__import__\n"
        "_blocked = tuple(filter(None, os.environ.get('TTS_BLOCKED_IMPORTS', '').split(',')))\n"
        "\n"
        "def _guard(name, globals=None, locals=None, fromlist=(), level=0):\n"
        "    for blocked in _blocked:\n"
        "        if name == blocked or name.startswith(blocked + '.'):\n"
        "            raise RuntimeError(f'blocked import: {name}')\n"
        "    return _real_import(name, globals, locals, fromlist, level)\n"
        "\n"
        "builtins.__import__ = _guard\n",
        encoding="utf-8",
    )
    env = dict(os.environ)
    existing_pythonpath = env.get("PYTHONPATH")
    env["PYTHONPATH"] = (
        f"{tmp_path}{os.pathsep}{existing_pythonpath}" if existing_pythonpath else str(tmp_path)
    )
    env["TTS_BLOCKED_IMPORTS"] = (
        "numpy,torch,core.bootstrap,core.backends,core.backends.torch_backend"
    )

    completed = subprocess.run(
        [
            sys.executable,
            "-m",
            "launcher",
            "--project-root",
            str(PROJECT_ROOT),
            "bootstrap-env",
            "--family",
            "qwen",
            "--module",
            "server",
        ],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        check=False,
        env=env,
    )

    assert completed.returncode == 0, completed.stderr
    payload = json.loads(completed.stdout)
    assert payload["bootstrap_env"]["family"] == "qwen"
